name: Terraform CI

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.hcl'
      - '.github/workflows/ha-rds-terraform-ci.yml'

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  TF_VERSION: '1.9.0'
  AWS_REGION: 'us-east-1'
  WORKING_DIR: 'environments/dev'

jobs:
  terraform-ci:
    name: Terraform CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume:
            arn:aws:iam::221717898536:role/ha-rds-GitHubActions-TerraformCI
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=backend.hcl
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          softfail: false 
          skip-check: CKV2_AWS_5,CKV_AWS_338

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
          exit-code: 1
          severity: 'HIGH,CRITICAL'
          

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan
        working-directory: ${{ env.WORKING_DIR }}
